version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./data/web:/vol/web
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=trello
      - POSTGRES_USER=trello
      - POSTGRES_PASSWORD=123@456

volumes:
  postgres-data:
