# Generated by Django 3.2.8 on 2021-12-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='password',
            field=models.CharField(default='4892', max_length=4),
        ),
    ]
