# Generated by Django 3.2.8 on 2021-12-21 05:52

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_otprequest_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='password',
            field=models.CharField(default=users.utils.generate_otp_password, max_length=4),
        ),
    ]
